<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JPMORGAN_LOANS_BusinessEntities\JPMORGAN_LOANS_BusinessEntities.csproj" />
    <ProjectReference Include="..\JPMORGAN_LOANS_DbConnectivity\JPMORGAN_LOANS_DbConnectivity.csproj" />
  </ItemGroup>

</Project>
